#端口号
server:
  port: 7000
#微服务名称#nacos
spring:
  application:
    name: getaway
  cloud:
#路由配置
    gateway:
      routes:
        - id: getaway #唯一标签
          uri:  lb://service-wechat #lb://xxx xxx是注册服务里面的服务
          predicates:
            - Path=/lbs/v1/user/query-user-info/login**
          filters: #去掉前面的lbs访问/lbs/web实际访问/web
            - StripPrefix=1
        - id: getaway
          uri: lb://service-wechat
          predicates:
            - Path=/lbs/v1/user/query-user-info/register**
          filters:
            - StripPrefix=1



    nacos:
      server-addr: localhost:8848












